### ISSUE TITLE
allow installing custom set of plugins at startup of confluence

### ISSUE THREAD

**Issue by sami-alajrami** [Praqma/confluence-server#4]
by passing a list of plugin IDs as an env var and letting the docker-entrypoint.sh download the plugins from https://marketplace.atlassian.com/download/plugins/ `<<plugin ID>>` into /plugins directory in the container/volume 

this will get confluence started with the needed plugins installed before hand.
This applies to Jira and bitbucket similarly I guess

**Comment by sami-alajrami** [comment]
If plugins are needed, the helm chart will be passing an env var called `PLUGINS_TO_INSTALL` which contains a list of plugin IDs separated with a `;` 
Otherwise, this env var will be empty

**Comment by sheeeng** [comment]
Confluence does not load plugins from `${CONFLUENCE_HOME}/plugins` directory.
We need to investigate other [alternatives](https://community.atlassian.com/t5/Confluence-questions/installing-a-confluence-plugin-via-filesystem/qaq-p/105527).
