### ISSUE TITLE
Datacenter logic forgets to add its own ip to the peer list

### ISSUE THREAD

**Issue by hoeghh** [Praqma/confluence-server#6]
After fetching the list of ip (endpoints from the service) the entrypoint forgets to add itself to the list.

If we have 3 nodes as (10.0.0.5, 10.0.0.6 and 10.0.0.7) they should have these lists
Node 1:
<property name="confluence.cluster.peers">10.0.0.5</property>

Node 2:
<property name="confluence.cluster.peers">10.0.0.5, 10.0.0.6</property>

Node 3:
<property name="confluence.cluster.peers">10.0.0.5, 10.0.0.6, 10.0.0.7</property>

Right now they only get the other nodes ip, forgetting its own.
In my case, Node 3 had this peer list : 
    <property name="confluence.cluster.peers">20.0.0.4,20.0.192.2</property>

**Comment by KamranAzeem** [comment]
done.
